// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhtQKPwe7eFaoOzdaAKXKswkD2ZWPpmpw',
    appId: '1:726131066975:web:91c2d3be46b3eafc2a73ea',
    messagingSenderId: '726131066975',
    projectId: 'colonyforumapp',
    authDomain: 'colonyforumapp.firebaseapp.com',
    storageBucket: 'colonyforumapp.appspot.com',
    measurementId: 'G-0YYEWJXFZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1EpKZVngj0by7oMbYeP7NC3QsgcljYl8',
    appId: '1:726131066975:android:91f682ab558111c92a73ea',
    messagingSenderId: '726131066975',
    projectId: 'colonyforumapp',
    storageBucket: 'colonyforumapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJPoxGNjG-y_6gS38h1B1tyLTbniu7Dmg',
    appId: '1:726131066975:ios:94bba1ea572a95d12a73ea',
    messagingSenderId: '726131066975',
    projectId: 'colonyforumapp',
    storageBucket: 'colonyforumapp.appspot.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJPoxGNjG-y_6gS38h1B1tyLTbniu7Dmg',
    appId: '1:726131066975:ios:df60b146f3603ca12a73ea',
    messagingSenderId: '726131066975',
    projectId: 'colonyforumapp',
    storageBucket: 'colonyforumapp.appspot.com',
    iosBundleId: 'com.example.newApp.RunnerTests',
  );
}
